swagger: "2.0"
info:
  description: "API to invoke training job"
  version: "0.1.0"
  title: "EMR deployment service"
  license:
    name: "GPLv3"
host: "localhost:5000"
basePath: "/v1"
schemes:
- "http"
paths:
  /runjob:
    post:
      tags:
      - "EMR"
      summary: "Invoke retraining job"
      description: ""
      operationId: "runjob"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/job"
  /versions:
    post:
      tags:
      - "EMR"
      summary: "Return precision and recall for each version"
      description: ""
      operationId: "versions"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/versions"

definitions:
  job:
    type: "object"
    properties:
      JobFlowId:
        type: "string"
      ResponseMetadata:
        type: "object"
        properties:
          RequestId:
            type: "string"
          HTTPStatusCode:
            type: "string"
          HTTPHeaders:
            type: "object"
            properties:
              x-amzn-requestid:
                type: "string"
              content-type:
                type: "string"
              content-length:
                type: "string"
              date:
                type: "string"
          RetryAttempts:
            type: "integer"
  versions:
    type: "object"
    items:
      type: "object"
      properties:
        precision:
          type: "string"
        recall:
          type: "string"
